version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - apps/api/.env
    environment:
      - MYSQL_ROOT_PASSWORD=testing
      - MYSQL_DATABASE=buyerbridge
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
